import { IJavaAPICommonResponse } from '../types';

import { marketAPIInst } from './instance';

export interface IFetchMatchedMarketsParam {
  code: string;
  bigMarket?: number;
  smallMarket?: number;
  // [HKEX,SHMK,SZMK,USA,FUND]
  tradeMarket?: string;
}

// Generated by https://quicktype.io

export interface IFetchMatchedMarketsResponse {
  bigMarket: number;
  code: string;
  smallMarket: number;
  tradeMarket: string;
  name?: string;
}

export function fetchMatchedMarkets(params: IFetchMatchedMarketsParam[]) {
  return marketAPIInst.post<IJavaAPICommonResponse<IFetchMatchedMarketsResponse[]>>('/symbol/getMarketByType', params);
}

// 小市场转大市场
export async function fetchMarketsBySmallMarket(
  data: {
    smallMarket: number;
    code: string;
  }[],
) {
  return marketAPIInst.post<IJavaAPICommonResponse<IFetchMatchedMarketsResponse[]>>('/symbol/getMarket', data);
}
