export const EVENT_KEY = {
  QUOTE_CHART_SETTING_UPDATE: 'QUOTE_CHART_SETTING_UPDATE',
  QUOTE_CHART_PERIOD_CHANGE: 'QUOTE_CHART_PERIOD_CHANGE',
  WARRANTS_AND_CBBC_CHOSEN_CALLBACK: 'WARRANTS_AND_CBBC_CHOSEN_CALLBACK',
  SUBSCRIBE_QUOTES_PACKAGE_SUCCESS: 'SUBSCRIBE_QUOTES_PACKAGE_SUCCESS',
};
