import type { Configuration } from '@/cfg';
import { writeFile } from 'node:fs/promises';

import { join } from 'node:path';

export function writeMultiPlatform(cfg: Configuration) {
  const { rootPath, isSP } = cfg;

  if (isSP)
    return;

  const { platform, pageType } = cfg.MPConfiguration;

  writeFile(
    join(rootPath, './helpers/multi-platforms.ts'),
    `// 📢 Do not manually modify, automatically generated by ESBoot.\nexport * from '@${platform}-${pageType}/helpers/multi-platforms';\n`,
  ).catch((err) => {
    console.error(`generate multi-platforms.ts failed: ${err.message}`);
  });
}
