import {
  Environment,
  JsMinifier,
  CSSMinifier,
  PLATFORMS,
  PAGE_TYPE,
} from '@dz-web/esboot-common/constants';

import { DEFAULT_DEV_PORT } from '@dz-web/esboot-common/constants';
import type { Configuration } from './types';

export const defaultCfg: Configuration = {
  isDev: true,
  isSP: false,
  rootPath: '',
  MPConfiguration: {
    pageType: PAGE_TYPE.browser,
    platform: PLATFORMS.PC,
    configRootPathOfPlatfrom: '',
    configRootPathOfPageType: '',
    contentRootPath: '',
  },
  configRootPath: '',
  configJSPath: '',
  env: Environment.dev,
  ipv4: 'localhost',
  version: '',
  entry: {},
  externals: {},
  cwd: process.cwd(),
  staticPathList: [],
  bundler: null,
  bundlerOptions: {},
  analyze: false,
  outputPath: 'dist',
  publicPath: '/',
  alias: {},
  px2rem: {},
  svgr: true,
  svgrOptions: {},
  isMobile: false,
  isBrowser: true,
  minimize: true,
  useTailwindcss: true,
  isCIBuild: false,
  legacy: false,
  define: {},
  copy: {},
  jsMinifier: JsMinifier.terser,
  jsMinifierOptions: {},
  cssMinifier: CSSMinifier.cssnano,
  cssMinifierOptions: {},
  useLangJsonPicker: false,
  sourceMap: false,
  server: {
    host: '0.0.0.0',
    open: false,
    port: DEFAULT_DEV_PORT,
  },
  plugins: [],
  experimental: {
    reactCompiler: {
      enable: true,
      target: '19',
    },
  },
};
