import { fileURLToPath } from 'node:url';

const resolvePath = (p) => fileURLToPath(import.meta.resolve(p));

export default {
  extends: [resolvePath('stylelint-config-standard')],
  plugins: [
    resolvePath('stylelint-scss'),
    resolvePath('@stylistic/stylelint-plugin'),
  ],
  customSyntax: resolvePath('postcss-scss'),
  ignoreFiles: ['!src/**/*', 'node_modules'],
  rules: {
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'extend',
          'at-root',
          'debug',
          'warn',
          'error',
          'if',
          'else',
          'for',
          'each',
          'while',
          'mixin',
          'include',
          'content',
          'return',
          'function',
          'use',
        ],
      },
    ],
    'selector-max-id': [
      1,
      {
        ignoreContextFunctionalPseudoClasses: [':not', '/^:(h|H)as$/'],
      },
    ],
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['global', 'local'],
      },
    ],
    'import-notation': 'string',
    'max-nesting-depth': 2,
    'color-function-notation': 'legacy',
    'color-function-alias-notation': 'with-alpha',
    "function-name-case": "lower",
    '@stylistic/color-hex-case': 'lower',
    '@stylistic/function-comma-space-after': 'always',
    '@stylistic/function-comma-space-before': 'never',
    '@stylistic/max-empty-lines': 1,
    '@stylistic/function-parentheses-space-inside': 'never',
    '@stylistic/function-whitespace-after': 'always',
    '@stylistic/number-leading-zero': 'never',
    '@stylistic/number-no-trailing-zeros': true,
    '@stylistic/string-quotes': 'single',
    '@stylistic/unit-case': 'lower',
    '@stylistic/value-list-comma-space-after': 'always',
    '@stylistic/value-list-comma-space-before': 'never',
    '@stylistic/value-list-max-empty-lines': 0,
    '@stylistic/property-case': 'lower',
    '@stylistic/declaration-bang-space-after': 'never',
    '@stylistic/declaration-bang-space-before': 'always',
    '@stylistic/declaration-colon-space-after': 'always',
    '@stylistic/declaration-colon-space-before': 'never',
    '@stylistic/declaration-block-semicolon-newline-after': 'always',
    '@stylistic/declaration-block-semicolon-space-before': 'never',
    '@stylistic/declaration-block-trailing-semicolon': 'always',
    '@stylistic/block-closing-brace-empty-line-before': 'never',
    '@stylistic/block-closing-brace-newline-after': 'always-multi-line',
    '@stylistic/block-opening-brace-newline-after': 'always',
    '@stylistic/block-closing-brace-newline-before': 'always',
    '@stylistic/block-opening-brace-space-before': 'always',
    '@stylistic/selector-attribute-brackets-space-inside': 'never',
    '@stylistic/selector-attribute-operator-space-after': 'never',
    '@stylistic/selector-attribute-operator-space-before': 'never',
    '@stylistic/selector-combinator-space-after': 'always',
    '@stylistic/selector-combinator-space-before': 'always',
    '@stylistic/selector-descendant-combinator-no-non-space': true,
    '@stylistic/selector-max-empty-lines': 0,
    '@stylistic/selector-pseudo-class-case': 'lower',
    '@stylistic/selector-pseudo-class-parentheses-space-inside': 'never',
    '@stylistic/selector-pseudo-element-case': 'lower',
    '@stylistic/selector-list-comma-newline-after': 'always',
    '@stylistic/selector-list-comma-newline-before': 'never-multi-line',
    '@stylistic/media-feature-colon-space-after': 'always',
    '@stylistic/media-feature-colon-space-before': 'never',
    '@stylistic/media-feature-name-case': 'lower',
    '@stylistic/media-feature-parentheses-space-inside': 'never',
    '@stylistic/media-feature-range-operator-space-after': 'always',
    '@stylistic/media-feature-range-operator-space-before': 'always',
    '@stylistic/media-query-list-comma-newline-after': 'always',
    '@stylistic/media-query-list-comma-space-before': 'never',
    '@stylistic/at-rule-name-case': 'lower',
    '@stylistic/at-rule-name-newline-after': 'always-multi-line',
    '@stylistic/at-rule-name-space-after': 'always-single-line',
    '@stylistic/indentation': 2,
    '@stylistic/linebreaks': 'unix',
    '@stylistic/max-empty-lines': 1,
    '@stylistic/no-empty-first-line': true,
    '@stylistic/no-extra-semicolons': true,
    '@stylistic/no-missing-end-of-source-newline': true,
    '@stylistic/unicode-bom': 'never',
    '@stylistic/no-eol-whitespace': true,
  },
};
